namenode:
    image: molab/hadoop
    ports:
        - "50070:50070"
    command: hdfs namenode
    hostname: hdfs-namenode
    restart: always

datanode:
    image: molab/hadoop
    command: hdfs datanode
    restart: always
    ports:
        - "50075"
    links:
        - namenode:hdfs-namenode

secondarynamenode:
    image: molab/hadoop
    command: hdfs secondarynamenode
    restart: always
    ports:
        - "50090:50090"
    links:
        - namenode:hdfs-namenode

yarn:
    image: molab/hadoop
    command: start-yarn.sh
    hostname: yarn
    restart: always
    ports:
     - "8088:8088"
     - "8042:8042"
    links:
     - namenode:hdfs-namenode
